import { AuthProvider } from "@/providers/AuthProvider"
import { ClientProviders } from "@/providers/ClientProviders"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "CV-Matic",
  description: "Generated by your interns",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ClientProviders>
          <AuthProvider>{children}</AuthProvider>
        </ClientProviders>
      </body>
    </html>
  )
}
