import { ClientProviders } from '@/providers/ClientProviders'
import { ServerProviders } from '@/providers/ServerProviders'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CV-Matic',
  description: 'Generated by your interns',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const messages = await getMessages()
  const locale = await getLocale()

  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ClientProviders>
            <ServerProviders>{children}</ServerProviders>
          </ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
